<?php
$data='[
	"Mahal",
	"Sitabuldi",
	"Dhantoli",
	"Itwari",
	"Mominpura",
	"Dharampeth",
	"Ramdaspeth",
	"Shraddhanand Peth",
	"Sadar",
	"Civil Lines",
	"Gandhibagh",
	"Nandanvan",
	"Kalamna",
	"Wardhaman Nagar",
	"Seminary Hills",
	"Police Line Takli",
	"Mankapur",
	"Pachpaoli",
	"Vayusena Nagar",
	"Ravi Nagar",
	"Byramji Town",
	"Chaoni",
	"Mangalwari",
	"Gaddi Godam",
	"Gitti Khadan",
	"Pratap Nagar",
	"Ajni",
	"Pardi",
	"Indora",
	"Maskasath",
	"Jaripatka",
	"Ashok Nagar",
	"Gokulpeth",
	"Giripeth",
	"Bajaj Nagar",
	"Rajendra Nagar",
	"Lakadganj",
	"Gandhinagar",
	"Manish Nagar",
	"Bezanbagh",
	"Bhandewadi",
	"Rahate Colony"
]';

return json_decode($data);	